# Spring Boot configuration
spring:
  profiles:
    active: development
# DATASOURCE (DataSourceProperties)
  datasource:
    url: jdbc:postgresql://qnap:5432/xxxxxx
    username: xxxxxx
    password: xxxxxxxxx
    driver-class-name: org.postgresql.Driver


# JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: ERROR
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    org.hibernate: ERROR
# Server configuration
server:
  port: 8082
  sessionTimeout: 30

# Security configuration
#security:
#  user:
#    name: user
#    password: user



format:
  date: yyyy-MM-dd


